### ISSUE TITLE
Clarification: Performance of Vern9

### ISSUE THREAD

**Issue by lindnemi** [PerezHz/TaylorIntegration.jl#125]
Hello, very interesting package!

I just looked through the docs and found that you are comparing taylorintegration to `Vern9`. I was surprised to see that this higher order explicit method fails to visit the second mass and noticed that you are calling the solver with

`solV = solve(prob, Vern9(), abstol=1e-20); #solve `prob` with the `Vern9` method`
 
that is, the `reltol` value is not set, in which case it should default to `reltol=1e-3` (see [here](https://diffeq.sciml.ai/stable/basics/common_solver_opts/)), at least this is what happens for lower order methods. Do you get the same qualitative behaviour for 

`solV = solve(prob, Vern9(), reltol = 1e-20, abstol=1e-20);`?

**Comment by PerezHz** [comment]
Hi, @lindnemi!

Thank you for pointing out this; I took a look and indeed it seems like adding a lower `reltol` indeed helps the performance of `Vern9`. I noticed that if I put `abstol=1e-20, reltol=1e-20` with `Vern9` the integration takes really long to finish (it performs more than 1e6 iterations), but found a good balance accuracy/speed with `abstol=1e-15, reltol=1e-15`.

I'd be in favor of updating this example with sensible values for `reltol`, so that the comparison is better. Also I noticed that the call to `TaylorMethod(25)` does not use `@taylorize`, which really helps performance for `TaylorIntegration.jl`, what do you think @lbenet?

**Comment by lbenet** [comment]
Thanks @lindnemi for the clarification. I do agree that it is important to be fair!

@PerezHz I also agree that the example should be adapted to include `@taylorize` if we are comparing performances.

**Comment by lindnemi** [comment]
Wow, that got fixed quickly. Exciting to see the updated results and explanation.
