### ISSUE TITLE
"Query Regarding Multi-precision Usage in TaylorIntegration: Error with BigFloats"

### ISSUE THREAD

**Issue by PPorras** [PerezHz/TaylorIntegration.jl#175]
Dear TaylorIntegration developers,

I am attempting to use multi-precision (`**BigFloats**`) with `**taylorinteg**`, but I am encountering an issue. When running my code, I obtain the following error:

`LoadError: MethodError: no method matching setindex!(::Taylor1{Float64}, ::BigFloat, ::Int64)`

I would like to know if it is possible to use `**BigFloats**` with `**taylorinteg**` and how I can address this error. Please guide me on this matter.

I appreciate your assistance in advance.

Best regards,

**Comment by PerezHz** [comment]
Hi there!

Can you please send a simple example with the code that you're running? In principle it should be possible to do it (we actually test it, see e.g. [here](https://github.com/PerezHz/TaylorIntegration.jl/blob/main/test/bigfloats.jl)). But if you give us an example we can try to figure out what the issue is.

**Comment by lbenet** [comment]
> LoadError: MethodError: no method matching setindex!(::Taylor1{Float64}, ::BigFloat, ::Int64)

As Jorge says, it is possible to use `taylorinteg` with `BigFloat`s. The error is showing that you are trying to construct a `Taylor1{Float64}` using a `BigFloat` (probably as the constant term), so you have to be sure that you are constructing a `Taylor1{BigFloat}`.

**Comment by PPorras** [comment]
Thank you very much for the guidance; I resolved the issue successfully.
