### ISSUE TITLE
Align dynamics function arguments to DifferentialEquations API

### ISSUE THREAD

**Issue by jessebett** [PerezHz/TaylorIntegration.jl#69]
Currently `jetcoeffs!(eqsdiff!::Function, t, x, dx, xaux)` expects `eqsdiff!` to follow with `taylorinteg` so `f!(t, x, dx)`. However, it would be much cleaner if this followed the updated DifferentialEquations.jl convention, where in-place dynamics equations are given as `f!(dx,x,p,t)` where `p` are parameters for `f!`. 

e.g. https://docs.juliadiffeq.org/stable/tutorials/ode_example.html#Example-2:-Solving-Systems-of-Equations-1

**Comment by lbenet** [comment]
Thanks for the suggestion! 

Some time ago, we discussed this with @PerezHz, and it is certainly something to consider. While the core of `TaylorIntegration` would require minor modifications (at least for the "typical cases"), it is not clear to me if `@taylorize` would be so easily handled. `@taylorize` is important because it allows to construct more efficient (internal) implementations of `jetcoeffs!` for the specific `f!`.

Please give us a bit of time to think this over and play around!

**Comment by lbenet** [comment]
See #70

**Comment by lbenet** [comment]
Closing, since #70 has been merged and v0.5.0 has been tagged.
